TumiGuide/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('guide/', include('guide.urls')),
    path('admin/', admin.site.urls),
]

guide/urls.py
from django.urls import path

from . import views

app_name = "guide"
urlpatterns = [
    path('', views.index, name='index'),
    path('places/', views.AddPlaceView.as_view(), name='place'),
    path('places/<int:pk>/', views.PlaceDetailView.as_view(), name='place_detail'),
    path('places/<int:pk>/edit', views.PlaceUpdateView.as_view(), name='place_update'),
    path('places/index/', views.PlaceListView.as_view(), name='place_index'),
    path('places/<int:pk>/delete/', views.PlaceDeleteView.as_view(), name='place_delete'),
    path('topics/', views.AddTopicView.as_view(), name='topic'),
    path('topics/<int:pk>/', views.TopicDetailView.as_view(), name='topic_detail'),
    path('topics/<int:pk>/edit', views.TopicUpdateView.as_view(), name='topic_update'),
    path('topics/index/', views.TopicListView.as_view(), name='topic_index'),
    path('topics/<int:pk>/delete/', views.TopicDeleteView.as_view(), name='topic_delete'),
    path('entries/', views.AddEntryView.as_view(), name='entry'),
    path('entries/<int:pk>/', views.EntryDetailView.as_view(), name='entry_detail'),
    path('entries/<int:pk>/edit', views.EntryUpdateView.as_view(), name='entry_update'),
    path('entries/index/', views.EntryListView.as_view(), name='entry_index'),
    path('entries/<int:pk>/delete/', views.EntryDeleteView.as_view(), name='entry_delete'),
]

guide/models.py
from unittest.util import _MAX_LENGTH
from django.db import models
from django.urls import reverse
from django.core.exceptions import ValidationError

def validate_titlecase(value):
    if value != value.title():
        raise ValidationError("First letter of each word must be uppercase")

# Create your models here.
class Place(models.Model):
    title = models.CharField(max_length=200, null=False, blank=False, unique=True, validators=[validate_titlecase])

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('guide:place_detail', kwargs={'pk': self.pk})
    
class Topic(models.Model):
    title = models.CharField(max_length = 200, null=False, blank=False, unique=True, validators=[validate_titlecase])

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("guide:topic_detail", kwargs={"pk": self.pk})

    #def save(self, *args, **kwargs):
        #titlelist = self.title.split()
        #cappedlist = []
        #for word in titlelist:
            #cappedlist.append(word.capitalize())
        #self.title = " ".join(cappedlist)
        #super().save(*args, **kwargs)

class Entry(models.Model):
    place   = models.ForeignKey(Place, on_delete=models.CASCADE)
    topic   = models.ForeignKey(Topic, on_delete=models.CASCADE)
    title   = models.CharField(max_length = 200, null=False, blank=False, validators=[validate_titlecase])
    details = models.TextField(null=False, blank=False)

    def get_absolute_url(self):
        return reverse("guide:entry_detail", kwargs={"pk": self.pk})
    
    

guide/forms.py
from django import forms

from .models import Place, Topic, Entry

class PlaceForm(forms.ModelForm):
    class Meta:
        model = Place
        fields = ["title"]

        widgets ={
            "title": forms.TextInput(attrs = {"class": "form-control", "placeholder" : "Use Title Case Format"})
        }

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ["title"]

        widgets ={
            "title": forms.TextInput(attrs = {"class": "form-control", "placeholder" : "Use Title Case Format"})
        }

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = [
            "place",
            "topic",
            "title",
            "details"
        ]

        widgets ={
            "place": forms.Select(attrs = {"class": "form-select"}),
            "topic": forms.Select(attrs = {"class": "form-select"}),
            "title": forms.TextInput(attrs = {"class": "form-control", "placeholder" : "Use Title Case Format"}),
            "details": forms.Textarea(attrs = {"class": "form-control", "rows": 5}),
        }

guide/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect, Http404
from .models import Place, Topic, Entry
from .forms import PlaceForm, TopicForm, EntryForm
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import DetailView, ListView
from django.urls import reverse_lazy, reverse
from django.contrib.messages.views import SuccessMessageMixin


def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

class AddPlaceView(SuccessMessageMixin, CreateView):
    model = Place
    form_class = PlaceForm
    template_name = "guide/places.html"
    success_message = "Place was successfully created"

class PlaceDetailView(DetailView):
    model = Place
    template_name = "guide/place_detail.html"

class PlaceUpdateView(SuccessMessageMixin, UpdateView):
    model = Place
    form_class = PlaceForm
    template_name = "guide/place_update.html"
    success_message = "Place was successfully updated"

class PlaceListView(ListView):
    model = Place
    template_name = "guide/place_list.html"

class PlaceDeleteView(SuccessMessageMixin, DeleteView):
    model = Place
    success_url = reverse_lazy("guide:place_index")
    success_message = "Place was successfully destroyed"


#def create_place(request):
    #return HttpResponse("You're looking at a list of places")
    #if request.method == "POST":
        #form = PlaceForm(request.POST) # can be (request.POST or None)
        #if form.is_valid():
            #new_place = form.save() # use .create instead?
            
            #return HttpResponseRedirect(reverse("guide:place_detail", args=[new_place.pk])) #create and add a success page url    
    #else:
        #form = PlaceForm()

    #context = {
        #"form": form
    #}
    #return render(request, "guide/places.html", context)

#def place_detail(request, place_id):
    #try:
        #place = Place.objects.get(pk=place_id)
    #except Place.DoesNotExist:
        #raise Http404("Place does not exist")
    
    #context = {"place": place}

    #return render(request, "guide/place_detail.html", context)


class AddTopicView(SuccessMessageMixin, CreateView):
    model = Topic
    form_class = TopicForm
    template_name = "guide/topics.html"
    success_message = "Topic was successfully created"

class TopicDetailView(DetailView):
    model = Topic
    template_name = "guide/topic_detail.html"

class TopicUpdateView(SuccessMessageMixin, UpdateView):
    model = Topic
    form_class = TopicForm
    template_name = "guide/topic_update.html"
    success_message = "Topic was successfully updated"

class TopicListView(ListView):
    model = Topic
    template_name = "guide/topic_list.html"

class TopicDeleteView(SuccessMessageMixin, DeleteView):
    model = Topic
    success_url = reverse_lazy("guide:topic_index")
    success_message = "Topic was successfully destroyed"
    
    
   

#def entry(request):
    #return HttpResponse("You're looking at table of entries")
    #all_place_objects = Place.objects.all()
    #all_topic_objects = Topic.objects.all()
    
    #context = {
        #"place_object" : all_place_objects,
        #"topic_object" : all_topic_objects
    #}
    #return render(request, "guide/entries.html", context)

class AddEntryView(SuccessMessageMixin, CreateView):
    model = Entry
    form_class = EntryForm
    template_name = "guide/entries.html"
    success_message = "Entry was successfully created"

class EntryDetailView(DetailView):
    model = Entry
    template_name = "guide/entry_detail.html"

class EntryUpdateView(SuccessMessageMixin, UpdateView):
    model = Entry
    form_class = EntryForm
    template_name = "guide/entry_update.html"
    success_message = "Entry was successfully updated"

class EntryListView(ListView):
    model = Entry
    template_name = "guide/entry_list.html"

class EntryDeleteView(SuccessMessageMixin, DeleteView):
    model = Entry
    success_url = reverse_lazy("guide:entry_index")
    success_message = "Entry was successfully destroyed"

guide/templates/guide/base.html
<!DOCTYPE html>
<html>
    <head>
        <style type="text/css">
            .turbo-progress-bar {
                position: fixed;
                display: block;
                top: 0;
                left: 0;
                height: 3px;
                background: #0076ff;
                z-index: 9999;
                transition:
                width 300ms ease-out,
                opacity 150ms 150ms ease-in;
                transform: translate3d(0, 0, 0);
            }

            .errorlist {
                color: red;
                list-style-type: none;
            }
        </style>
        <link rel="stylesheet" href="/assets/application-e0cf9d8fcb18bf7f909d8d91a5e78499f82ac29523d475bf3a9ab265d5e2b451.css" data-turbo-track="reload">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <script type="importmap" data-turbo-track="reload">
            {
                "imports": {
                "application": "/assets/application-37f365cbecf1fa2810a8303f4b6571676fa1f9c56c248528bc14ddb857531b95.js",
                "@hotwired/turbo-rails": "/assets/turbo.min-e5023178542f05fc063cd1dc5865457259cc01f3fba76a28454060d33de6f429.js",
                "@hotwired/stimulus": "/assets/stimulus.min-b8a9738499c7a8362910cd545375417370d72a9776fb4e766df7671484e2beb7.js",
                "@hotwired/stimulus-loading": "/assets/stimulus-loading-1fc59770fb1654500044afd3f5f6d7d00800e5be36746d55b94a2963a7a228aa.js",
                "controllers/application": "/assets/controllers/application-368d98631bccbf2349e0d4f8269afb3fe9625118341966de054759d96ea86c7e.js",
                "controllers/hello_controller": "/assets/controllers/hello_controller-549135e8e7c683a538c3d6d517339ba470fcfb79d62f738a0a089ba41851a554.js",
                "controllers": "/assets/controllers/index-2db729dddcc5b979110e98de4b6720f83f91a123172e87281d5a58410fc43806.js"
                }
            }
        </script>
        <script src="/assets/es-module-shims.min-d89e73202ec09dede55fb74115af9c5f9f2bb965433de1c2446e1faa6dac2470.js" async="async" data-turbo-track="reload"></script>
        <script type="module">import "application"</script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.min.js" integrity="sha384-ODmDIVzN+pFdexxHEHFBQH3/9/vQ9uori45z4JjnFsRydbmQbmL5t1tQ0culUzyK" crossorigin="anonymous"></script>
  
        <title>TumiGuide</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
        <meta name="csrf-param" content="authenticity_token">
        <meta name="csrf-token" content="4ob7q7Z5XEQt6iwbbATmejs85Jnu0AasDlUAU_em-1Z6sbsjGENLeem5kRp91vU1GSxzG9GF5m3-VcaT1h3GmQ">
        <link rel="modulepreload" href="/assets/application-37f365cbecf1fa2810a8303f4b6571676fa1f9c56c248528bc14ddb857531b95.js">
        <link rel="modulepreload" href="/assets/turbo.min-e5023178542f05fc063cd1dc5865457259cc01f3fba76a28454060d33de6f429.js">
        <link rel="modulepreload" href="/assets/stimulus.min-b8a9738499c7a8362910cd545375417370d72a9776fb4e766df7671484e2beb7.js">
        <link rel="modulepreload" href="/assets/stimulus-loading-1fc59770fb1654500044afd3f5f6d7d00800e5be36746d55b94a2963a7a228aa.js">
    </head>
  
    <body>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'guide:entry_index' %}">TravelGuide</a>
    
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'guide:entry' %}">Entries</a> 
                        </li>
  
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'guide:place' %}">Places</a>  
                        </li>
                    
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'guide:topic' %}">Topics</a>  
                        </li>
                    </ul>
        
                </div>
            </div>
        </nav>
        <main>
            
            {% block content %}
            replace me
            {% endblock %}
        
        </main>
        
    </body>
</html>

guide/templates/guide/entries.html
{% extends "guide/base.html" %}

{% block content %}
    <div class="container">
        <br>
        <h1>New entry</h1>

        <form method="POST"> {% csrf_token%}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Create Entry">
        </form>

        <br>
        <div>
            <a href="{% url 'guide:entry_index' %}">Back to entries</a>
        </div>
    </div>
{% endblock %}

guide/templates/guide/entry_detail.html
{% extends "guide/base.html" %}

{% block content %}
    
<div class="container">
  <br>
  {% if messages %}
  <!--<ul class="messages">-->
    {% for message in messages %}
    <p style="color: green">{{ message }}</p>
    {% endfor %}
  <!--</ul>-->
  {% endif %}
  <!--<p style="color: green">Topic was successfully created.</p>-->

  <div>
    <p>
    <strong>Title:</strong> {{entry.title}}
    </p>
    <p>
    <strong>Details:</strong> {{entry.details}}
    </p>
    <p>
    <strong>Place:</strong> {{entry.place}}
    </p>
    <p>
    <strong>Topic:</strong> {{entry.topic}}
    </p>
  </div>


  <div>
    <a href="{% url 'guide:entry_update' entry.id %}">Edit this entry</a> | <!-- link to update view page -->
    <a href="{% url 'guide:entry_index' %}">Back to entries</a>

    <form method="POST" action="{% url 'guide:entry_delete' entry.id %}"> {% csrf_token %} <!--not sure what I'm doing-->
      <button type="submit">Destroy this entry</button>
    </form>
  </div>

</div>

{% endblock %}

guide/templates/guide/entry_list.html
{% extends "guide/base.html" %}

{% block content %}

<div class="container">
    <br>
    {% if messages %}
    <!--<ul class="messages">-->
        {% for message in messages %}
        <p style="color: green">{{ message }}</p>
        {% endfor %}
    <!--</ul>-->
    {% endif %}

    <h1>Entries</h1>

    <div> <!--delete id? id="topics"-->
        <a href="{% url 'guide:entry' %}">New entry</a> <!-- links to entry create view -->
        
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">#</th> <!--scope="col"-->
                    <th scope="col">Place</th> <!--scope="col"-->
                    <th scope="col">Topic</th> <!--scope="col"-->
                    <th scope="col">Title</th> <!--scope="col"-->
                    <th scope="col">Details</th> <!--scope="col"-->
                    <th scope="col"></th> <!--scope="col"-->
                </tr>
            </thead>
            <tbody>
                {% for entry in object_list %}
                <tr>
                    <th scope="row">{{ entry.pk }}</th> <!---->
                    <th class="text-muted">{{ entry.place }}</th> <!---->
                    <th class="text-muted">{{ entry.topic }}</th> <!--class="text-muted"-->
                    <th class="text-muted">{{ entry.title }}</th> <!--class="text-muted"-->
                    <th class="text-muted">{{ entry.details }}</th> <!--class="text-muted"-->
                    <th><a href="{{entry.get_absolute_url}}">Show this entry</a></th>
                </tr>
                {% endfor %} 
            </tbody>

        </table>
    </div>
</div>

{% endblock %}










<div class="container">
    <br>
    <p style="color: green"></p>

<h1>Entries</h1>

<div id="entries">
<a href="/entries/new">New entry</a>
<table class="table table-striped ">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Place</th>
      <th scope="col">Topic</th>
      <th scope="col">Title</th>
      <th scope="col">Details</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>

   <tr>
   <th scope="row">3</th>
   <th class="text-muted">Kumasi</th>
   <th class="text-muted">Restaurants &amp; Bars</th>
   <th class="text-muted">It's my kitchen</th>
   <th class="text-muted">Local and Chinese fo...</th>
   <th><a href="/entries/3">Show this entry</a></th>
   </tr> 
   <tr>
   <th scope="row">4</th>
   <th class="text-muted">Kumasi</th>
   <th class="text-muted">Sites to visit</th>
   <th class="text-muted">Manhyia Palace(Ashanti king's Palace</th>
   <th class="text-muted">To know more about t...</th>
   <th><a href="/entries/4">Show this entry</a></th>
   </tr> 
   <tr>
   <th scope="row">5</th>
   <th class="text-muted">Kumasi</th>
   <th class="text-muted">Sites to visit</th>
   <th class="text-muted">Armed forces museum </th>
   <th class="text-muted">The armed forces mus...</th>
   <th><a href="/entries/5">Show this entry</a></th>
   </tr> 
   <tr>
   <th scope="row">6</th>
   <th class="text-muted">Kumasi</th>
   <th class="text-muted">Sites to visit</th>
   <th class="text-muted">Central market/Kejetia</th>
   <th class="text-muted">It the west Africa's...</th>
   <th><a href="/entries/6">Show this entry</a></th>
   </tr> 
   <tr>
   <th scope="row">7</th>
   <th class="text-muted">Kumasi</th>
   <th class="text-muted">Sites to visit</th>
   <th class="text-muted">KNUST botanical garden </th>
   <th class="text-muted">The Kwame Nkrumah Un...</th>
   <th><a href="/entries/7">Show this entry</a></th>
   </tr> 
   <tr>
   <th scope="row">8</th>
   <th class="text-muted">Kumasi</th>
   <th class="text-muted">Sites to visit</th>
   <th class="text-muted">Massage </th>
   <th class="text-muted">The massage center i...</th>
   <th><a href="/entries/8">Show this entry</a></th>
   </tr> 
   <tr>
   <th scope="row">9</th>
   <th class="text-muted">Kumasi</th>
   <th class="text-muted">Sites to visit</th>
   <th class="text-muted">Culture Center </th>
   <th class="text-muted">Mini museum (ethnogr...</th>
   <th><a href="/entries/9">Show this entry</a></th>
   </tr> 
   <tr>
   <th scope="row">10</th>
   <th class="text-muted">Kumasi</th>
   <th class="text-muted">Sites to visit</th>
   <th class="text-muted">Komfo Anokye Sword </th>
   <th class="text-muted">The immovable Sword ...</th>
   <th><a href="/entries/10">Show this entry</a></th>
   </tr> 
   <tr>
   <th scope="row">11</th>
   <th class="text-muted">Kumasi</th>
   <th class="text-muted">Sites to visit</th>
   <th class="text-muted">Swimming </th>
   <th class="text-muted">Golden Tulip hotel,t...</th>
   <th><a href="/entries/11">Show this entry</a></th>
   </tr> 
   <tr>
   <th scope="row">12</th>
   <th class="text-muted">Kumasi</th>
   <th class="text-muted">Sites to visit</th>
   <th class="text-muted">Rattray park</th>
   <th class="text-muted">It a nice park with ...</th>
   <th><a href="/entries/12">Show this entry</a></th>
   </tr> 
   <tr>
   <th scope="row">13</th>
   <th class="text-muted">Kumasi</th>
   <th class="text-muted">Sites to visit</th>
   <th class="text-muted">Brass Shop</th>
   <th class="text-muted">Banner Agyemang,0243...</th>
   <th><a href="/entries/13">Show this entry</a></th>
   </tr> 
   <tr>
   <th scope="row">14</th>
   <th class="text-muted">Kumasi</th>
   <th class="text-muted">Sites to visit</th>
   <th class="text-muted">Adawomase Village </th>
   <th class="text-muted">Ecovillage to learn ...</th>
   <th><a href="/entries/14">Show this entry</a></th>
   </tr> 
   <tr>
   <th scope="row">15</th>
   <th class="text-muted">Kumasi</th>
   <th class="text-muted">Sites to visit</th>
   <th class="text-muted">Adawomase Village </th>
   <th class="text-muted">Ecovillage to learn ...</th>
   <th><a href="/entries/15">Show this entry</a></th>
   </tr> 
   <tr>
   <th scope="row">16</th>
   <th class="text-muted">Kumasi</th>
   <th class="text-muted">Sites to visit</th>
   <th class="text-muted">Ntonso Village </th>
   <th class="text-muted">Learn about the Adin...</th>
   <th><a href="/entries/16">Show this entry</a></th>
   </tr> 
   <tr>
   <th scope="row">17</th>
   <th class="text-muted">Kumasi</th>
   <th class="text-muted">Sites to visit</th>
   <th class="text-muted">Bobiri Wildlife Sanctuary </th>
   <th class="text-muted">Nice beautiful lands...</th>
   <th><a href="/entries/17">Show this entry</a></th>
   </tr> 
   <tr>
   <th scope="row">18</th>
   <th class="text-muted">Kumasi</th>
   <th class="text-muted">Sites to visit</th>
   <th class="text-muted">BRONZE MAKING FACTORY TOUR </th>
   <th class="text-muted">If you are intereste...</th>
   <th><a href="/entries/18">Show this entry</a></th>
   </tr> 
   <tr>
   <th scope="row">19</th>
   <th class="text-muted">Accra</th>
   <th class="text-muted">Accomodation</th>
   <th class="text-muted">Harriet</th>
   <th class="text-muted">test test...</th>
   <th><a href="/entries/19">Show this entry</a></th>
   </tr> 
   <tr>
   <th scope="row">21</th>
   <th class="text-muted">Accra</th>
   <th class="text-muted">Accomodation</th>
   <th class="text-muted">fjoiejofw</th>
   <th class="text-muted">kpwjefpe...</th>
   <th><a href="/entries/21">Show this entry</a></th>
   </tr> 
   <tr>
   <th scope="row">22</th>
   <th class="text-muted">Accra</th>
   <th class="text-muted">Accomodation</th>
   <th class="text-muted">imho</th>
   <th class="text-muted">gyugu...</th>
   <th><a href="/entries/22">Show this entry</a></th>
   </tr> 
   <tr>
   <th scope="row">23</th>
   <th class="text-muted">Accra</th>
   <th class="text-muted">Accomodation</th>
   <th class="text-muted">blow</th>
   <th class="text-muted">klnwne...</th>
   <th><a href="/entries/23">Show this entry</a></th>
   </tr> 
  </tbody>




    
  

</table></div></div>

guide/templates/guide/entry_update.html
{% extends "guide/base.html" %}

{% block content %}
    
    <div class="container">
        <br>
        <h1>Editing entry</h1>
  
        <form method="POST"> {% csrf_token%}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Update Entry">
        </form>
  
        <br>
        <div>
            <a href="{{entry.get_absolute_url}}">Show this entry</a> | <!-- links to detail page without message -->
            <a href="{% url 'guide:entry_index' %}">Back to entries</a> <!-- links to All topics page without message -->
        </div>
    </div>

{% endblock %}

guide/templates/guide/place_detail.html
{% extends "guide/base.html" %}

{% block content %}
    
<div class="container">
  <br>
  {% if messages %}
  <!--<ul class="messages">-->
    {% for message in messages %}
    <p style="color: green">{{ message }}</p>
    {% endfor %}
  <!--</ul>-->
  {% endif %}
  

  <div>
    <p>
     <strong>Title:</strong>{{place.title}}
    </p>
  </div>


  <div>
    <a href="{% url 'guide:place_update' place.id %}">Edit this place</a> |
    <a href="{% url 'guide:place_index' %}">Back to places</a>

    <form method="post" action="{% url 'guide:place_delete' place.id %}"> {% csrf_token %}
      <button type="submit">Destroy this place</button>
    </form>
  </div>

</div>

{% endblock %}

guide/templates/guide/place_list.html
{% extends "guide/base.html" %}

{% block content %}

<div class="container">
    <br>
    {% if messages %}
    <!--<ul class="messages">-->
        {% for message in messages %}
        <p style="color: green">{{ message }}</p>
        {% endfor %}
    <!--</ul>-->
    {% endif %}

    <h1>Places</h1>

    <div> <!--delete id? id="topics"-->
        {% for place in object_list %}
        <div> <!--delete id?  id="topic_1"-->
            <p><strong>Title:</strong> {{ place.title }}</p>
        </div>
        <p><a href="{{place.get_absolute_url}}">Show this place</a></p> <!-- links to topic detail view -->
        {% endfor %}
    </div>

    <a href="{% url 'guide:place' %}">New place</a> <!-- links to topic create view -->
</div>

{% endblock %}

guide/templates/guide/place_update.html
{% extends "guide/base.html" %}

{% block content %}
    
    <div class="container">
        <br>
        <h1>Editing place</h1>
  
        <form method="POST"> {% csrf_token%}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>
  
        <br>
        <div>
            <a href="{{place.get_absolute_url}}">Show this place</a> |
            <a href="{% url 'guide:place_index' %}">Back to places</a> 
        </div>
    </div>

{% endblock %}

guide/templates/guide/topic_detail.html
{% extends "guide/base.html" %}

{% block content %}
    
<div class="container">
  <br>
  {% if messages %}
  <!--<ul class="messages">-->
    {% for message in messages %}
    <p style="color: green">{{ message }}</p>
    {% endfor %}
  <!--</ul>-->
  {% endif %}
  <!--<p style="color: green">Topic was successfully created.</p>-->

  <div>
    <p>
     <strong>Title:</strong> {{topic.title}}
    </p>
  </div>


  <div>
    <a href="{% url 'guide:topic_update' topic.id %}">Edit this topic</a> | <!-- link to update view page -->
    <a href="{% url 'guide:topic_index' %}">Back to topics</a>

    <form method="POST" action="{% url 'guide:topic_delete' topic.id %}"> {% csrf_token %} <!--not sure what I'm doing-->
      <button type="submit">Destroy this topic</button>
    </form>
  </div>

</div>

{% endblock %}

guide/templates/guide/topic_list.html
{% extends "guide/base.html" %}

{% block content %}

<div class="container">
    <br>
    {% if messages %}
    <!--<ul class="messages">-->
        {% for message in messages %}
        <p style="color: green">{{ message }}</p>
        {% endfor %}
    <!--</ul>-->
    {% endif %}

    <h1>Topics</h1>

    <div> <!--delete id? id="topics"-->
        {% for topic in object_list %}
        <div> <!--delete id?  id="topic_1"-->
            <p><strong>Title:</strong> {{ topic.title }}</p>
        </div>
        <p><a href="{{topic.get_absolute_url}}">Show this topic</a></p> <!-- links to topic detail view -->
        {% endfor %}
    </div>

    <a href="{% url 'guide:topic' %}">New topic</a> <!-- links to topic create view -->
</div>

{% endblock %}

guide/templates/guide/topic_update.html
{% extends "guide/base.html" %}

{% block content %}
    
    <div class="container">
        <br>
        <h1>Editing topic</h1>
  
        <form method="POST"> {% csrf_token%}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>
  
        <br>
        <div>
            <a href="{{topic.get_absolute_url}}">Show this topic</a> | <!-- links to detail page without message -->
            <a href="{% url 'guide:topic_index' %}">Back to topics</a> <!-- links to All topics page without message -->
        </div>
    </div>

{% endblock %}